name: integration
on:
  pull_request:
    branches: [ main ]

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  GH_REF: ${{ github.ref }} 

jobs: 
  build-test: 
    runs-on: ubuntu-latest
    steps: 
      # git checkout 
      - name: checkout code
        uses: actions/checkout@v3
      
      # set up python version 
      - name: set up python 
        uses: actions/setup-python@v4
        with: 
          python-version: 3.9

      # install python dependencies 
      - name: install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r transform/dbt/requirements.txt
      
      # install dbt packages
      - name: dbt deps
        run: |
          cd transform/dbt/adventureworks
          dbt deps

      # run sqlfluff linting
      - name: sql linting
        run: sqlfluff lint transform/dbt/adventureworks

      # checkout to main 
      - name: checkout to main
        uses: actions/checkout@v3
        with:
          ref: main
      
      # generate dbt manifest.json
      - name: generate dbt manifest 
        run: | 
          cd transform/dbt/adventureworks
          dbt deps
          dbt compile --target prod
      
      # publish manifest.json
      - name: upload dbt manifest 
        uses: actions/upload-artifact@v3
        with: 
          name: manifest.json
          path: transform/dbt/adventureworks/target/manifest.json

      # checkout back to current branch 
      - name: checkout to current branch 
        uses: actions/checkout@v3

      # download manifest.json to current working directory 
      - uses: actions/download-artifact@v3
        with:
          name: manifest.json
          path: transform/dbt/adventureworks

      # dbt run and test changed models with state modified flag 
      - name: dbt run and test state modified 
        run: | 
          cd transform/dbt/adventureworks
          dbt deps
          dbt run -m state:modified+1 --defer --state . --target ci
          dbt test -m state:modified+1 --defer --state . --target ci
